In [4]:
import numpy as np

a = np.zeros((3,3,2))
np.shape(a)

b = np.array([[1,2,3],
              [2,3,4],
              [3,4,5]])
a[:, :, 0] = b
print(a[:, :, 0])


[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]
