In [11]:
%matplotlib inline

In [27]:
import numpy as np 
z = np.zeros((3,3,2))
a = np.array([[1,1,1],
              [1,1,1],
              [1,1,1]])
b = np.array([[2,2,2],
              [2,2,2],
              [2,2,2]])

a @ b

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [13]:
z[:, :, 1] = a
np.mean(z)



1.5

In [16]:
z[:, :, 1]

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])

In [25]:
k = np.zeros((2, 1, 3))
k.flatten(1)


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  


array([0., 0., 0., 0., 0., 0.])

In [24]:
np.squeeze(k).shape



(2, 3)